import {
  CircleDot,
  ChevronsUpDown,
  ChevronDown,
  Frame as FrameIcon,
  LoaderCircle,
  RectangleHorizontal,
  ScrollText,
  SlidersHorizontal,
  SquareCheck,
  TextCursorInput,
  ToggleLeft,
  Type,
  LayoutGrid,
} from "lucide-react";
import type { FrameworkDef, PropSpec, WidgetDef } from "@/frameworks/types";
import {
  options,
  pBool,
  pColor,
  pList,
  pNumber,
  pSelect,
  pText,
} from "@/frameworks/props";

const ANCHOR = options("center", "n", "e", "s", "w", "nw", "ne", "sw", "se");
const JUSTIFY = options("center", "left", "right");
const STATE = options("normal", "disabled");
const WEIGHT = options("normal", "bold");
const ORIENT = options("horizontal", "vertical");
const MODE = options("determinate", "indeterminate");
const WRAP = options("word", "char", "none");

const TRANSPARENT = "transparent";

const fontProps = (size: number): PropSpec[] => [
  pText("font_family", "", "Font", {
    group: "Text",
    default: "Arial",
    virtual: true,
    placeholder: "Arial",
  }),
  pNumber("font_size", "", "Size", {
    group: "Text",
    default: size,
    min: 6,
    max: 200,
    virtual: true,
  }),
  pSelect("font_weight", "", "Weight", WEIGHT, {
    group: "Text",
    default: "normal",
    virtual: true,
  }),
];

const FONT = {
  kwarg: "font",
  familyKey: "font_family",
  sizeKey: "font_size",
  weightKey: "font_weight",
  fallbackFamily: "Arial",
  fallbackSize: 14,
};

const surface = (key: string, label: string, fallback?: string): PropSpec =>
  pColor(key, key, label, {
    default: fallback,
    transparentValue: TRANSPARENT,
  });

const widgets: WidgetDef[] = [
  {
    key: "CTkLabel",
    label: "Label",
    icon: Type,
    category: "Display",
    ctor: "ctk.CTkLabel",
    varPrefix: "label",
    sizing: "px",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "Label" }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Background"),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        max: 200,
      }),
      pSelect("anchor", "anchor", "Anchor", ANCHOR, { default: "center" }),
      pSelect("justify", "justify", "Justify", JUSTIFY, { default: "center" }),
      pNumber("width", "width", "Width", { min: 0 }),
      pNumber("height", "height", "Height", { min: 0 }),
    ],
    visual: {
      shape: "text",
      text: "text",
      fg: "text_color",
      bg: "fg_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      fontWeight: "font_weight",
      align: "justify",
      width: "width",
      height: "height",
      padX: 4,
      padY: 2,
    },
  },
  {
    key: "CTkButton",
    label: "Button",
    icon: RectangleHorizontal,
    category: "Input",
    ctor: "ctk.CTkButton",
    varPrefix: "button",
    sizing: "px",
    font: FONT,
    fixed: { command: "@on_button_click" },
    props: [
      pText("text", "text", "Text", { default: "Button" }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#ffffff" }),
      surface("fg_color", "Background", "#3b82f6"),
      pBool("hover", "hover", "Hover effect", { default: true }),
      pColor("hover_color", "hover_color", "Hover color", {
        default: "#2563eb",
      }),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 0,
        max: 40,
      }),
      surface("border_color", "Border color", "#3b82f6"),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 140, min: 0 }),
      pNumber("height", "height", "Height", { default: 32, min: 0 }),
      pSelect("anchor", "anchor", "Anchor", ANCHOR, { default: "center" }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "button",
      text: "text",
      fg: "text_color",
      bg: "fg_color",
      borderWidth: "border_width",
      borderColor: "border_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      fontWeight: "font_weight",
      width: "width",
      height: "height",
      boxWidth: 140,
      boxHeight: 32,
    },
  },
  {
    key: "CTkEntry",
    label: "Entry",
    icon: TextCursorInput,
    category: "Input",
    ctor: "ctk.CTkEntry",
    varPrefix: "entry",
    sizing: "px",
    font: FONT,
    props: [
      pText("placeholder_text", "placeholder_text", "Placeholder", {
        default: "Enter text",
      }),
      pText("show", "show", "Mask char", {
        group: "Behavior",
        placeholder: "e.g. *",
      }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      pColor("placeholder_text_color", "placeholder_text_color", "Hint color", {
        default: "#9ca3af",
      }),
      surface("fg_color", "Background", "#ffffff"),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 2,
        max: 40,
      }),
      surface("border_color", "Border color", "#d1d5db"),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pSelect("justify", "justify", "Justify", JUSTIFY, { default: "left" }),
      pNumber("width", "width", "Width", { default: 140, min: 0 }),
      pNumber("height", "height", "Height", { default: 32, min: 0 }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "field",
      text: "placeholder_text",
      fallbackText: "Entry",
      fg: "placeholder_text_color",
      bg: "fg_color",
      borderWidth: "border_width",
      borderColor: "border_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "width",
      height: "height",
      boxWidth: 140,
      boxHeight: 32,
    },
  },
  {
    key: "CTkCheckBox",
    label: "CheckBox",
    icon: SquareCheck,
    category: "Input",
    ctor: "ctk.CTkCheckBox",
    varPrefix: "checkbox",
    sizing: "px",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "CheckBox" }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Check color", "#3b82f6"),
      pColor("hover_color", "hover_color", "Hover color", {
        default: "#2563eb",
      }),
      surface("border_color", "Border color", "#d1d5db"),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 3,
        max: 40,
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pNumber("checkbox_width", "checkbox_width", "Box width", {
        default: 24,
        min: 8,
        max: 200,
      }),
      pNumber("checkbox_height", "checkbox_height", "Box height", {
        default: 24,
        min: 8,
        max: 200,
      }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "check",
      text: "text",
      fg: "text_color",
      accent: "fg_color",
      borderColor: "border_color",
      borderWidth: "border_width",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "checkbox_width",
      height: "checkbox_height",
    },
  },
  {
    key: "CTkRadioButton",
    label: "RadioButton",
    icon: CircleDot,
    category: "Input",
    ctor: "ctk.CTkRadioButton",
    varPrefix: "radiobutton",
    sizing: "px",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "RadioButton" }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Dot color", "#3b82f6"),
      pColor("hover_color", "hover_color", "Hover color", {
        default: "#2563eb",
      }),
      surface("border_color", "Border color", "#d1d5db"),
      pNumber("border_width_checked", "border_width_checked", "Border on", {
        group: "Appearance",
        default: 6,
        max: 40,
      }),
      pNumber("border_width_unchecked", "border_width_unchecked", "Border off", {
        group: "Appearance",
        default: 3,
        max: 40,
      }),
      pNumber("radiobutton_width", "radiobutton_width", "Dot width", {
        default: 22,
        min: 8,
        max: 200,
      }),
      pNumber("radiobutton_height", "radiobutton_height", "Dot height", {
        default: 22,
        min: 8,
        max: 200,
      }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "radio",
      text: "text",
      fg: "text_color",
      accent: "fg_color",
      borderColor: "border_color",
      borderWidth: "border_width_unchecked",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "radiobutton_width",
      height: "radiobutton_height",
    },
  },
  {
    key: "CTkSwitch",
    label: "Switch",
    icon: ToggleLeft,
    category: "Input",
    ctor: "ctk.CTkSwitch",
    varPrefix: "switch",
    sizing: "px",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "Switch" }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Track off", "#d1d5db"),
      surface("progress_color", "Track on", "#3b82f6"),
      surface("button_color", "Knob", "#ffffff"),
      pColor("button_hover_color", "button_hover_color", "Knob hover", {
        default: "#f3f4f6",
      }),
      pNumber("switch_width", "switch_width", "Switch width", {
        default: 40,
        min: 10,
        max: 400,
      }),
      pNumber("switch_height", "switch_height", "Switch height", {
        default: 20,
        min: 6,
        max: 200,
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 10,
        max: 200,
      }),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 3,
        max: 40,
      }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "switch",
      text: "text",
      fg: "text_color",
      track: "fg_color",
      accent: "progress_color",
      knob: "button_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "switch_width",
      height: "switch_height",
    },
  },
  {
    key: "CTkSlider",
    label: "Slider",
    icon: SlidersHorizontal,
    category: "Input",
    ctor: "ctk.CTkSlider",
    varPrefix: "slider",
    sizing: "px",
    props: [
      pNumber("from_", "from_", "From", { group: "Behavior", max: 100000 }),
      pNumber("to", "to", "To", {
        group: "Behavior",
        default: 100,
        max: 100000,
      }),
      pNumber("number_of_steps", "number_of_steps", "Steps", {
        group: "Behavior",
        max: 1000,
      }),
      surface("fg_color", "Track", "#d1d5db"),
      surface("progress_color", "Progress", "#3b82f6"),
      surface("button_color", "Knob", "#2563eb"),
      pColor("button_hover_color", "button_hover_color", "Knob hover", {
        default: "#1d4ed8",
      }),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 6,
        max: 40,
      }),
      pSelect("orientation", "orientation", "Orientation", ORIENT, {
        default: "horizontal",
      }),
      pNumber("width", "width", "Width", { default: 200, min: 0 }),
      pNumber("height", "height", "Height", { default: 16, min: 0 }),
    ],
    visual: {
      shape: "slider",
      track: "fg_color",
      accent: "progress_color",
      knob: "button_color",
      width: "width",
      height: "height",
      boxWidth: 200,
      boxHeight: 16,
    },
  },
  {
    key: "CTkProgressBar",
    label: "ProgressBar",
    icon: LoaderCircle,
    category: "Display",
    ctor: "ctk.CTkProgressBar",
    varPrefix: "progressbar",
    sizing: "px",
    props: [
      surface("fg_color", "Track", "#d1d5db"),
      surface("progress_color", "Progress", "#3b82f6"),
      surface("border_color", "Border color"),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        max: 40,
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 8,
        max: 200,
      }),
      pSelect("orientation", "orientation", "Orientation", ORIENT, {
        default: "horizontal",
      }),
      pSelect("mode", "mode", "Mode", MODE, {
        group: "Behavior",
        default: "determinate",
      }),
      pNumber("width", "width", "Width", { default: 200, min: 0 }),
      pNumber("height", "height", "Height", { default: 16, min: 0 }),
    ],
    visual: {
      shape: "progress",
      track: "fg_color",
      accent: "progress_color",
      borderWidth: "border_width",
      borderColor: "border_color",
      radius: "corner_radius",
      width: "width",
      height: "height",
      boxWidth: 200,
      boxHeight: 16,
    },
  },
  {
    key: "CTkComboBox",
    label: "ComboBox",
    icon: ChevronsUpDown,
    category: "Input",
    ctor: "ctk.CTkComboBox",
    varPrefix: "combobox",
    sizing: "px",
    font: FONT,
    props: [
      pList("values", "values", "Values", {
        default: ["Option 1", "Option 2", "Option 3"],
      }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Background", "#ffffff"),
      surface("border_color", "Border color", "#d1d5db"),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 2,
        max: 40,
      }),
      surface("button_color", "Button", "#3b82f6"),
      pColor("button_hover_color", "button_hover_color", "Button hover", {
        default: "#2563eb",
      }),
      surface("dropdown_fg_color", "Dropdown bg", "#ffffff"),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 160, min: 0 }),
      pNumber("height", "height", "Height", { default: 32, min: 0 }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "dropdown",
      items: "values",
      fg: "text_color",
      bg: "fg_color",
      accent: "button_color",
      borderWidth: "border_width",
      borderColor: "border_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "width",
      height: "height",
      boxWidth: 160,
      boxHeight: 32,
    },
  },
  {
    key: "CTkOptionMenu",
    label: "OptionMenu",
    icon: ChevronDown,
    category: "Input",
    ctor: "ctk.CTkOptionMenu",
    varPrefix: "optionmenu",
    sizing: "px",
    font: FONT,
    props: [
      pList("values", "values", "Values", {
        default: ["Option 1", "Option 2", "Option 3"],
      }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#ffffff" }),
      surface("fg_color", "Background", "#3b82f6"),
      surface("button_color", "Button", "#2563eb"),
      pColor("button_hover_color", "button_hover_color", "Button hover", {
        default: "#1d4ed8",
      }),
      surface("dropdown_fg_color", "Dropdown bg", "#ffffff"),
      pColor("dropdown_hover_color", "dropdown_hover_color", "Dropdown hover", {
        default: "#e5e7eb",
      }),
      pColor("dropdown_text_color", "dropdown_text_color", "Dropdown text", {
        default: "#000000",
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pSelect("anchor", "anchor", "Anchor", ANCHOR, { default: "w" }),
      pNumber("width", "width", "Width", { default: 160, min: 0 }),
      pNumber("height", "height", "Height", { default: 32, min: 0 }),
      pBool("dynamic_resizing", "dynamic_resizing", "Dynamic resizing", {
        default: true,
      }),
    ],
    visual: {
      shape: "dropdown",
      items: "values",
      fg: "text_color",
      bg: "fg_color",
      accent: "button_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "width",
      height: "height",
      boxWidth: 160,
      boxHeight: 32,
    },
  },
  {
    key: "CTkSegmentedButton",
    label: "SegmentedButton",
    icon: LayoutGrid,
    category: "Input",
    ctor: "ctk.CTkSegmentedButton",
    varPrefix: "segmentedbutton",
    sizing: "px",
    font: FONT,
    props: [
      pList("values", "values", "Values", {
        default: ["One", "Two", "Three"],
      }),
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Background", "#e5e7eb"),
      surface("selected_color", "Selected", "#3b82f6"),
      pColor("selected_hover_color", "selected_hover_color", "Selected hover", {
        default: "#2563eb",
      }),
      surface("unselected_color", "Unselected", "#e5e7eb"),
      pColor("unselected_hover_color", "unselected_hover_color", "Hover", {
        default: "#d1d5db",
      }),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 3,
        max: 40,
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 240, min: 0 }),
      pNumber("height", "height", "Height", { default: 32, min: 0 }),
    ],
    visual: {
      shape: "dropdown",
      items: "values",
      fg: "text_color",
      bg: "fg_color",
      accent: "selected_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "width",
      height: "height",
      boxWidth: 240,
      boxHeight: 32,
    },
  },
  {
    key: "CTkTextbox",
    label: "Textbox",
    icon: ScrollText,
    category: "Input",
    ctor: "ctk.CTkTextbox",
    varPrefix: "textbox",
    sizing: "px",
    font: FONT,
    props: [
      ...fontProps(14),
      pColor("text_color", "text_color", "Text color", { default: "#000000" }),
      surface("fg_color", "Background", "#ffffff"),
      surface("border_color", "Border color", "#d1d5db"),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        default: 2,
        max: 40,
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pSelect("wrap", "wrap", "Wrap", WRAP, {
        group: "Behavior",
        default: "word",
      }),
      pNumber("width", "width", "Width", { default: 240, min: 0 }),
      pNumber("height", "height", "Height", { default: 120, min: 0 }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "textarea",
      fallbackText: "Textbox",
      fg: "text_color",
      bg: "fg_color",
      borderWidth: "border_width",
      borderColor: "border_color",
      radius: "corner_radius",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "width",
      height: "height",
      boxWidth: 240,
      boxHeight: 120,
    },
  },
  {
    key: "CTkFrame",
    label: "Frame",
    icon: FrameIcon,
    category: "Layout",
    ctor: "ctk.CTkFrame",
    varPrefix: "frame",
    sizing: "px",
    props: [
      surface("fg_color", "Background", "#e5e7eb"),
      surface("border_color", "Border color", "#d1d5db"),
      pNumber("border_width", "border_width", "Border", {
        group: "Appearance",
        max: 40,
      }),
      pNumber("corner_radius", "corner_radius", "Radius", {
        group: "Appearance",
        default: 8,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 240, min: 0 }),
      pNumber("height", "height", "Height", { default: 160, min: 0 }),
    ],
    visual: {
      shape: "box",
      bg: "fg_color",
      borderWidth: "border_width",
      borderColor: "border_color",
      radius: "corner_radius",
      width: "width",
      height: "height",
      boxWidth: 240,
      boxHeight: 160,
    },
  },
];

export const CUSTOMTKINTER: FrameworkDef = {
  id: "customtkinter",
  label: "CustomTkinter",
  shortLabel: "CTk",
  tagline: "Modern themed widgets on top of Tk",
  module: "customtkinter",
  alias: "ctk",
  docsUrl: "https://customtkinter.tomschimansky.com/documentation/",
  accent: "#3b82f6",
  widgets,
  categories: ["Display", "Input", "Layout"],
  defaultWindow: { width: 900, height: 600, background: "#ffffff" },
};
