import {
  ChevronDown,
  CircleDot,
  Image as ImageIcon,
  LoaderCircle,
  MousePointerClick,
  RectangleHorizontal,
  SlidersHorizontal,
  Square,
  SquareCheck,
  SquareDashed,
  Star,
  TextCursorInput,
  ToggleLeft,
  Type,
} from "lucide-react";
import type { FrameworkDef, WidgetDef } from "@/frameworks/types";
import {
  coded,
  pBool,
  pColor,
  pList,
  pNumber,
  pSelect,
  pText,
} from "@/frameworks/props";

const WEIGHT = coded([
  ["normal", "Normal", "ft.FontWeight.NORMAL"],
  ["bold", "Bold", "ft.FontWeight.BOLD"],
  ["w_300", "Light", "ft.FontWeight.W_300"],
  ["w_500", "Medium", "ft.FontWeight.W_500"],
  ["w_900", "Black", "ft.FontWeight.W_900"],
]);

const TEXT_ALIGN = coded([
  ["left", "Left", "ft.TextAlign.LEFT"],
  ["center", "Center", "ft.TextAlign.CENTER"],
  ["right", "Right", "ft.TextAlign.RIGHT"],
  ["justify", "Justify", "ft.TextAlign.JUSTIFY"],
]);

const LABEL_POSITION = coded([
  ["right", "Right", "ft.LabelPosition.RIGHT"],
  ["left", "Left", "ft.LabelPosition.LEFT"],
]);

const IMAGE_FIT = coded([
  ["contain", "Contain", "ft.ImageFit.CONTAIN"],
  ["cover", "Cover", "ft.ImageFit.COVER"],
  ["fill", "Fill", "ft.ImageFit.FILL"],
  ["fit_width", "Fit width", "ft.ImageFit.FIT_WIDTH"],
  ["fit_height", "Fit height", "ft.ImageFit.FIT_HEIGHT"],
  ["none", "None", "ft.ImageFit.NONE"],
]);

const common = [
  pNumber("opacity", "opacity", "Opacity", {
    group: "Appearance",
    min: 0,
    max: 1,
    unit: "0-1",
  }),
  pText("tooltip", "tooltip", "Tooltip", { group: "Behavior" }),
  pBool("disabled", "disabled", "Disabled", { group: "Behavior" }),
];

const buttonProps = (fill: string, label: string) => [
  pText("text", "text", "Text", { default: label }),
  pText("icon", "icon", "Icon", {
    group: "Content",
    enumPrefix: "ft.Icons",
    placeholder: "e.g. save",
  }),
  pColor("color", "color", "Text color", { default: "#ffffff" }),
  pColor("bgcolor", "bgcolor", "Background", { default: fill }),
  pNumber("width", "width", "Width", { default: 150, min: 0 }),
  pNumber("height", "height", "Height", { default: 40, min: 0 }),
  ...common,
];

const widgets: WidgetDef[] = [
  {
    key: "Text",
    label: "Text",
    icon: Type,
    category: "Display",
    ctor: "ft.Text",
    varPrefix: "text",
    sizing: "px",
    props: [
      pText("value", "value", "Value", { default: "Text" }),
      pText("font_family", "font_family", "Font", {
        group: "Text",
        placeholder: "Roboto",
      }),
      pNumber("size", "size", "Size", {
        group: "Text",
        default: 16,
        min: 6,
        max: 200,
      }),
      pSelect("weight", "weight", "Weight", WEIGHT, {
        group: "Text",
        default: "normal",
      }),
      pBool("italic", "italic", "Italic", { group: "Text" }),
      pSelect("text_align", "text_align", "Align", TEXT_ALIGN, {
        group: "Text",
        default: "left",
      }),
      pColor("color", "color", "Text color", { default: "#000000" }),
      pColor("bgcolor", "bgcolor", "Background"),
      pNumber("width", "width", "Width", { min: 0 }),
      pNumber("height", "height", "Height", { min: 0 }),
      ...common,
    ],
    visual: {
      shape: "text",
      text: "value",
      fg: "color",
      bg: "bgcolor",
      fontSize: "size",
      fontFamily: "font_family",
      fontWeight: "weight",
      italic: "italic",
      align: "text_align",
      width: "width",
      height: "height",
      padX: 2,
      padY: 2,
    },
  },
  {
    key: "ElevatedButton",
    label: "ElevatedButton",
    icon: RectangleHorizontal,
    category: "Buttons",
    ctor: "ft.ElevatedButton",
    varPrefix: "button",
    sizing: "px",
    fixed: { on_click: "@on_button_click" },
    props: [
      ...buttonProps("#3b82f6", "Button"),
      pNumber("elevation", "elevation", "Elevation", {
        group: "Appearance",
        max: 40,
      }),
    ],
    visual: {
      shape: "button",
      text: "text",
      fg: "color",
      bg: "bgcolor",
      width: "width",
      height: "height",
      boxWidth: 150,
      boxHeight: 40,
    },
  },
  {
    key: "FilledButton",
    label: "FilledButton",
    icon: Square,
    category: "Buttons",
    ctor: "ft.FilledButton",
    varPrefix: "filled_button",
    sizing: "px",
    fixed: { on_click: "@on_button_click" },
    props: buttonProps("#2563eb", "Filled"),
    visual: {
      shape: "button",
      text: "text",
      fg: "color",
      bg: "bgcolor",
      width: "width",
      height: "height",
      boxWidth: 150,
      boxHeight: 40,
    },
  },
  {
    key: "OutlinedButton",
    label: "OutlinedButton",
    icon: SquareDashed,
    category: "Buttons",
    ctor: "ft.OutlinedButton",
    varPrefix: "outlined_button",
    sizing: "px",
    fixed: { on_click: "@on_button_click" },
    props: [
      pText("text", "text", "Text", { default: "Outlined" }),
      pText("icon", "icon", "Icon", {
        group: "Content",
        enumPrefix: "ft.Icons",
        placeholder: "e.g. save",
      }),
      pColor("color", "color", "Text color", { default: "#3b82f6" }),
      pColor("bgcolor", "bgcolor", "Background"),
      pNumber("width", "width", "Width", { default: 150, min: 0 }),
      pNumber("height", "height", "Height", { default: 40, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "button",
      text: "text",
      fg: "color",
      bg: "bgcolor",
      borderColor: "color",
      width: "width",
      height: "height",
      boxWidth: 150,
      boxHeight: 40,
    },
  },
  {
    key: "TextButton",
    label: "TextButton",
    icon: MousePointerClick,
    category: "Buttons",
    ctor: "ft.TextButton",
    varPrefix: "text_button",
    sizing: "px",
    fixed: { on_click: "@on_button_click" },
    props: [
      pText("text", "text", "Text", { default: "Text button" }),
      pText("icon", "icon", "Icon", {
        group: "Content",
        enumPrefix: "ft.Icons",
        placeholder: "e.g. save",
      }),
      pColor("color", "color", "Text color", { default: "#3b82f6" }),
      pColor("bgcolor", "bgcolor", "Background"),
      pNumber("width", "width", "Width", { default: 150, min: 0 }),
      pNumber("height", "height", "Height", { default: 40, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "button",
      text: "text",
      fg: "color",
      bg: "bgcolor",
      width: "width",
      height: "height",
      boxWidth: 150,
      boxHeight: 40,
    },
  },
  {
    key: "IconButton",
    label: "IconButton",
    icon: Star,
    category: "Buttons",
    ctor: "ft.IconButton",
    varPrefix: "icon_button",
    sizing: "px",
    fixed: { on_click: "@on_button_click" },
    props: [
      pText("icon", "icon", "Icon", {
        default: "favorite",
        enumPrefix: "ft.Icons",
      }),
      pColor("icon_color", "icon_color", "Icon color", { default: "#3b82f6" }),
      pNumber("icon_size", "icon_size", "Icon size", {
        group: "Text",
        default: 24,
        min: 6,
        max: 200,
      }),
      pColor("bgcolor", "bgcolor", "Background"),
      ...common,
    ],
    visual: {
      shape: "icon",
      text: "icon",
      fg: "icon_color",
      bg: "bgcolor",
      fontSize: "icon_size",
      boxWidth: 48,
      boxHeight: 48,
    },
  },
  {
    key: "TextField",
    label: "TextField",
    icon: TextCursorInput,
    category: "Input",
    ctor: "ft.TextField",
    varPrefix: "textfield",
    sizing: "px",
    props: [
      pText("label", "label", "Label", { default: "Label" }),
      pText("value", "value", "Value"),
      pText("hint_text", "hint_text", "Hint", { default: "Enter text" }),
      pBool("password", "password", "Password", { group: "Behavior" }),
      pBool("multiline", "multiline", "Multiline", { group: "Behavior" }),
      pBool("read_only", "read_only", "Read only", { group: "Behavior" }),
      pBool("filled", "filled", "Filled", { group: "Appearance" }),
      pNumber("text_size", "text_size", "Text size", {
        group: "Text",
        default: 14,
        min: 6,
        max: 200,
      }),
      pColor("color", "color", "Text color", { default: "#000000" }),
      pColor("bgcolor", "bgcolor", "Background", { default: "#ffffff" }),
      pColor("border_color", "border_color", "Border color", {
        default: "#d1d5db",
      }),
      pNumber("border_radius", "border_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 220, min: 0 }),
      pNumber("height", "height", "Height", { default: 48, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "field",
      text: "hint_text",
      fallbackText: "TextField",
      fg: "color",
      bg: "bgcolor",
      borderColor: "border_color",
      radius: "border_radius",
      fontSize: "text_size",
      width: "width",
      height: "height",
      boxWidth: 220,
      boxHeight: 48,
    },
  },
  {
    key: "Checkbox",
    label: "Checkbox",
    icon: SquareCheck,
    category: "Input",
    ctor: "ft.Checkbox",
    varPrefix: "checkbox",
    sizing: "px",
    props: [
      pText("label", "label", "Label", { default: "Checkbox" }),
      pBool("value", "value", "Checked", { group: "Behavior" }),
      pSelect("label_position", "label_position", "Label side", LABEL_POSITION, {
        default: "right",
      }),
      pColor("fill_color", "fill_color", "Fill", { default: "#3b82f6" }),
      pColor("check_color", "check_color", "Check", { default: "#ffffff" }),
      pNumber("width", "width", "Width", { min: 0 }),
      ...common,
    ],
    visual: {
      shape: "check",
      text: "label",
      accent: "fill_color",
      fg: "check_color",
      width: "width",
    },
  },
  {
    key: "Radio",
    label: "Radio",
    icon: CircleDot,
    category: "Input",
    ctor: "ft.Radio",
    varPrefix: "radio",
    sizing: "px",
    props: [
      pText("label", "label", "Label", { default: "Radio" }),
      pText("value", "value", "Value", {
        group: "Behavior",
        default: "option_1",
      }),
      pSelect("label_position", "label_position", "Label side", LABEL_POSITION, {
        default: "right",
      }),
      pColor("fill_color", "fill_color", "Fill", { default: "#3b82f6" }),
      pColor("active_color", "active_color", "Active", { default: "#2563eb" }),
      pNumber("width", "width", "Width", { min: 0 }),
      ...common,
    ],
    visual: {
      shape: "radio",
      text: "label",
      accent: "fill_color",
      width: "width",
    },
  },
  {
    key: "Switch",
    label: "Switch",
    icon: ToggleLeft,
    category: "Input",
    ctor: "ft.Switch",
    varPrefix: "switch",
    sizing: "px",
    props: [
      pText("label", "label", "Label", { default: "Switch" }),
      pBool("value", "value", "On", { group: "Behavior" }),
      pSelect("label_position", "label_position", "Label side", LABEL_POSITION, {
        default: "right",
      }),
      pColor("active_color", "active_color", "Track on", { default: "#3b82f6" }),
      pColor("thumb_color", "thumb_color", "Thumb", { default: "#ffffff" }),
      pColor("track_color", "track_color", "Track off", { default: "#d1d5db" }),
      pNumber("width", "width", "Width", { min: 0 }),
      ...common,
    ],
    visual: {
      shape: "switch",
      text: "label",
      accent: "active_color",
      track: "track_color",
      knob: "thumb_color",
      width: "width",
    },
  },
  {
    key: "Slider",
    label: "Slider",
    icon: SlidersHorizontal,
    category: "Input",
    ctor: "ft.Slider",
    varPrefix: "slider",
    sizing: "px",
    props: [
      pNumber("value", "value", "Value", {
        group: "Behavior",
        default: 50,
        max: 100000,
      }),
      pNumber("min", "min", "Min", { group: "Behavior", max: 100000 }),
      pNumber("max", "max", "Max", {
        group: "Behavior",
        default: 100,
        max: 100000,
      }),
      pNumber("divisions", "divisions", "Divisions", {
        group: "Behavior",
        max: 1000,
      }),
      pText("label", "label", "Label"),
      pColor("active_color", "active_color", "Active", { default: "#3b82f6" }),
      pColor("inactive_color", "inactive_color", "Inactive", {
        default: "#d1d5db",
      }),
      pColor("thumb_color", "thumb_color", "Thumb", { default: "#2563eb" }),
      pNumber("width", "width", "Width", { default: 220, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "slider",
      accent: "active_color",
      track: "inactive_color",
      knob: "thumb_color",
      width: "width",
      boxWidth: 220,
      boxHeight: 24,
    },
  },
  {
    key: "ProgressBar",
    label: "ProgressBar",
    icon: LoaderCircle,
    category: "Display",
    ctor: "ft.ProgressBar",
    varPrefix: "progress_bar",
    sizing: "px",
    props: [
      pNumber("value", "value", "Value", {
        group: "Behavior",
        min: 0,
        max: 1,
        unit: "0-1",
      }),
      pColor("color", "color", "Bar", { default: "#3b82f6" }),
      pColor("bgcolor", "bgcolor", "Track", { default: "#d1d5db" }),
      pNumber("bar_height", "bar_height", "Bar height", {
        default: 8,
        min: 1,
        max: 200,
      }),
      pNumber("border_radius", "border_radius", "Radius", {
        group: "Appearance",
        default: 4,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 220, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "progress",
      accent: "color",
      track: "bgcolor",
      radius: "border_radius",
      width: "width",
      height: "bar_height",
      boxWidth: 220,
      boxHeight: 8,
    },
  },
  {
    key: "Dropdown",
    label: "Dropdown",
    icon: ChevronDown,
    category: "Input",
    ctor: "ft.Dropdown",
    varPrefix: "dropdown",
    sizing: "px",
    props: [
      pText("label", "label", "Label", { default: "Dropdown" }),
      pList("options", "options", "Options", {
        default: ["Option 1", "Option 2", "Option 3"],
        itemCtor: "ft.dropdown.Option",
      }),
      pText("value", "value", "Value"),
      pBool("filled", "filled", "Filled", { group: "Appearance" }),
      pColor("color", "color", "Text color", { default: "#000000" }),
      pColor("bgcolor", "bgcolor", "Background", { default: "#ffffff" }),
      pColor("border_color", "border_color", "Border color", {
        default: "#d1d5db",
      }),
      pNumber("border_radius", "border_radius", "Radius", {
        group: "Appearance",
        default: 6,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 220, min: 0 }),
      pNumber("height", "height", "Height", { default: 48, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "dropdown",
      items: "options",
      text: "label",
      fg: "color",
      bg: "bgcolor",
      borderColor: "border_color",
      radius: "border_radius",
      width: "width",
      height: "height",
      boxWidth: 220,
      boxHeight: 48,
    },
  },
  {
    key: "Container",
    label: "Container",
    icon: Square,
    category: "Layout",
    ctor: "ft.Container",
    varPrefix: "container",
    sizing: "px",
    props: [
      pColor("bgcolor", "bgcolor", "Background", { default: "#e5e7eb" }),
      pNumber("border_radius", "border_radius", "Radius", {
        group: "Appearance",
        default: 8,
        max: 200,
      }),
      pNumber("padding", "padding", "Padding", { group: "Layout", max: 200 }),
      pNumber("margin", "margin", "Margin", { group: "Layout", max: 200 }),
      pNumber("width", "width", "Width", { default: 240, min: 0 }),
      pNumber("height", "height", "Height", { default: 160, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "box",
      bg: "bgcolor",
      radius: "border_radius",
      width: "width",
      height: "height",
      boxWidth: 240,
      boxHeight: 160,
    },
  },
  {
    key: "Image",
    label: "Image",
    icon: ImageIcon,
    category: "Display",
    ctor: "ft.Image",
    varPrefix: "image",
    sizing: "px",
    props: [
      pText("src", "src", "Source", {
        default: "https://picsum.photos/200",
        placeholder: "URL or path",
      }),
      pSelect("fit", "fit", "Fit", IMAGE_FIT, { default: "contain" }),
      pNumber("border_radius", "border_radius", "Radius", {
        group: "Appearance",
        default: 8,
        max: 200,
      }),
      pNumber("width", "width", "Width", { default: 160, min: 0 }),
      pNumber("height", "height", "Height", { default: 160, min: 0 }),
      ...common,
    ],
    visual: {
      shape: "image",
      text: "src",
      radius: "border_radius",
      width: "width",
      height: "height",
      boxWidth: 160,
      boxHeight: 160,
    },
  },
];

export const FLET: FrameworkDef = {
  id: "flet",
  label: "Flet",
  shortLabel: "Flet",
  tagline: "Flutter-powered controls in Python",
  module: "flet",
  alias: "ft",
  docsUrl: "https://flet.dev/docs/controls/",
  accent: "#22c55e",
  widgets,
  categories: ["Display", "Buttons", "Input", "Layout"],
  defaultWindow: { width: 900, height: 600, background: "#ffffff" },
};
