import {
  AlignLeft,
  Frame as FrameIcon,
  Hash,
  List,
  PenTool,
  RectangleHorizontal,
  ScrollText,
  SlidersHorizontal,
  SquareCheck,
  CircleDot,
  TextCursorInput,
  Type,
} from "lucide-react";
import type { FrameworkDef, PropSpec, WidgetDef } from "@/frameworks/types";
import { pyString } from "@/codegen/python";
import {
  options,
  pBool,
  pColor,
  pList,
  pNumber,
  pSelect,
  pText,
} from "@/frameworks/props";

const RELIEF = options("flat", "raised", "sunken", "groove", "ridge", "solid");
const ANCHOR = options("center", "n", "ne", "e", "se", "s", "sw", "w", "nw");
const JUSTIFY = options("left", "center", "right");
const STATE = options("normal", "disabled");
const WEIGHT = options("normal", "bold");
const WRAP = options("word", "char", "none");
const ORIENT = options("horizontal", "vertical");
const SELECTMODE = options("browse", "single", "multiple", "extended");

const fontProps = (size: number): PropSpec[] => [
  pText("font_family", "", "Font", {
    group: "Text",
    default: "Arial",
    virtual: true,
    placeholder: "Arial",
  }),
  pNumber("font_size", "", "Size", {
    group: "Text",
    default: size,
    min: 6,
    max: 200,
    virtual: true,
  }),
  pSelect("font_weight", "", "Weight", WEIGHT, {
    group: "Text",
    default: "normal",
    virtual: true,
  }),
];

const FONT = {
  kwarg: "font",
  familyKey: "font_family",
  sizeKey: "font_size",
  weightKey: "font_weight",
  fallbackFamily: "Arial",
  fallbackSize: 12,
};

const border = (width: number): PropSpec[] => [
  pSelect("relief", "relief", "Relief", RELIEF, { default: "flat" }),
  pNumber("borderwidth", "borderwidth", "Border", {
    group: "Appearance",
    default: width,
    max: 40,
  }),
];

const widgets: WidgetDef[] = [
  {
    key: "Label",
    label: "Label",
    icon: Type,
    category: "Display",
    ctor: "tk.Label",
    varPrefix: "label",
    sizing: "chars",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "Label" }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background"),
      ...border(0),
      pSelect("anchor", "anchor", "Anchor", ANCHOR, { default: "center" }),
      pSelect("justify", "justify", "Justify", JUSTIFY, { default: "center" }),
      pNumber("padx", "padx", "Pad X", { group: "Layout", max: 200 }),
      pNumber("pady", "pady", "Pad Y", { group: "Layout", max: 200 }),
      pNumber("width", "width", "Width", { unit: "chars", max: 400 }),
      pNumber("height", "height", "Height", { unit: "lines", max: 200 }),
    ],
    visual: {
      shape: "text",
      text: "text",
      fg: "fg",
      bg: "bg",
      fontSize: "font_size",
      fontFamily: "font_family",
      fontWeight: "font_weight",
      borderWidth: "borderwidth",
      align: "justify",
      width: "width",
      height: "height",
      padX: 2,
      padY: 2,
    },
  },
  {
    key: "Button",
    label: "Button",
    icon: RectangleHorizontal,
    category: "Input",
    ctor: "tk.Button",
    varPrefix: "button",
    sizing: "chars",
    font: FONT,
    fixed: { command: "@on_button_click" },
    props: [
      pText("text", "text", "Text", { default: "Button" }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background", { default: "#e5e7eb" }),
      pColor("activebackground", "activebackground", "Active bg", {
        default: "#d1d5db",
      }),
      pColor("activeforeground", "activeforeground", "Active text"),
      ...border(2),
      pNumber("padx", "padx", "Pad X", {
        group: "Layout",
        default: 6,
        max: 200,
      }),
      pNumber("pady", "pady", "Pad Y", {
        group: "Layout",
        default: 3,
        max: 200,
      }),
      pNumber("width", "width", "Width", { unit: "chars", max: 400 }),
      pNumber("height", "height", "Height", { unit: "lines", max: 200 }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "button",
      text: "text",
      fg: "fg",
      bg: "bg",
      fontSize: "font_size",
      fontFamily: "font_family",
      fontWeight: "font_weight",
      borderWidth: "borderwidth",
      width: "width",
      height: "height",
      padX: 8,
      padY: 4,
    },
  },
  {
    key: "Entry",
    label: "Entry",
    icon: TextCursorInput,
    category: "Input",
    ctor: "tk.Entry",
    varPrefix: "entry",
    sizing: "chars",
    font: FONT,
    props: [
      pText("show", "show", "Mask char", {
        group: "Behavior",
        placeholder: "e.g. *",
      }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background", { default: "#ffffff" }),
      pColor("insertbackground", "insertbackground", "Caret"),
      ...border(2),
      pSelect("justify", "justify", "Justify", JUSTIFY, { default: "left" }),
      pNumber("width", "width", "Width", {
        unit: "chars",
        default: 20,
        max: 400,
      }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "field",
      fallbackText: "Entry",
      fg: "fg",
      bg: "bg",
      fontSize: "font_size",
      fontFamily: "font_family",
      borderWidth: "borderwidth",
      width: "width",
      padX: 4,
      padY: 3,
    },
  },
  {
    key: "Checkbutton",
    label: "Checkbutton",
    icon: SquareCheck,
    category: "Input",
    ctor: "tk.Checkbutton",
    varPrefix: "checkbutton",
    sizing: "chars",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "Checkbutton" }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background"),
      pColor("selectcolor", "selectcolor", "Box color", { default: "#ffffff" }),
      pColor("activebackground", "activebackground", "Active bg"),
      ...border(0),
      pSelect("anchor", "anchor", "Anchor", ANCHOR, { default: "w" }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "check",
      text: "text",
      fg: "fg",
      bg: "bg",
      accent: "selectcolor",
      fontSize: "font_size",
      fontFamily: "font_family",
      borderWidth: "borderwidth",
    },
  },
  {
    key: "Radiobutton",
    label: "Radiobutton",
    icon: CircleDot,
    category: "Input",
    ctor: "tk.Radiobutton",
    varPrefix: "radiobutton",
    sizing: "chars",
    font: FONT,
    props: [
      pText("text", "text", "Text", { default: "Radiobutton" }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background"),
      pColor("selectcolor", "selectcolor", "Dot color", { default: "#ffffff" }),
      ...border(0),
      pNumber("value", "value", "Value", { group: "Behavior", max: 999 }),
      pSelect("anchor", "anchor", "Anchor", ANCHOR, { default: "w" }),
      pSelect("state", "state", "State", STATE, {
        group: "Behavior",
        default: "normal",
      }),
    ],
    visual: {
      shape: "radio",
      text: "text",
      fg: "fg",
      bg: "bg",
      accent: "selectcolor",
      fontSize: "font_size",
      fontFamily: "font_family",
    },
  },
  {
    key: "Listbox",
    label: "Listbox",
    icon: List,
    category: "Display",
    ctor: "tk.Listbox",
    varPrefix: "listbox",
    sizing: "chars",
    font: FONT,
    after: (varName, props) => {
      const items = Array.isArray(props.items) ? props.items : [];
      return items.map(
        (item, index) => `${varName}.insert(${index}, ${pyString(String(item))})`
      );
    },
    props: [
      pList("items", "", "Items", {
        default: ["Item 1", "Item 2", "Item 3"],
        virtual: true,
      }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background", { default: "#ffffff" }),
      pColor("selectbackground", "selectbackground", "Selection", {
        default: "#3b82f6",
      }),
      pColor("selectforeground", "selectforeground", "Selected text"),
      ...border(1),
      pSelect("selectmode", "selectmode", "Select mode", SELECTMODE, {
        group: "Behavior",
        default: "browse",
      }),
      pNumber("width", "width", "Width", {
        unit: "chars",
        default: 20,
        max: 400,
      }),
      pNumber("height", "height", "Height", {
        unit: "lines",
        default: 5,
        max: 200,
      }),
    ],
    visual: {
      shape: "list",
      items: "items",
      fg: "fg",
      bg: "bg",
      accent: "selectbackground",
      fontSize: "font_size",
      fontFamily: "font_family",
      borderWidth: "borderwidth",
      width: "width",
      height: "height",
      padX: 3,
      padY: 3,
    },
  },
  {
    key: "Text",
    label: "Text",
    icon: ScrollText,
    category: "Input",
    ctor: "tk.Text",
    varPrefix: "textbox",
    sizing: "chars",
    font: FONT,
    props: [
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background", { default: "#ffffff" }),
      pColor("insertbackground", "insertbackground", "Caret"),
      ...border(1),
      pSelect("wrap", "wrap", "Wrap", WRAP, {
        group: "Behavior",
        default: "word",
      }),
      pNumber("padx", "padx", "Pad X", { group: "Layout", max: 200 }),
      pNumber("pady", "pady", "Pad Y", { group: "Layout", max: 200 }),
      pNumber("width", "width", "Width", {
        unit: "chars",
        default: 30,
        max: 400,
      }),
      pNumber("height", "height", "Height", {
        unit: "lines",
        default: 6,
        max: 200,
      }),
    ],
    visual: {
      shape: "textarea",
      fallbackText: "Text",
      fg: "fg",
      bg: "bg",
      fontSize: "font_size",
      fontFamily: "font_family",
      borderWidth: "borderwidth",
      width: "width",
      height: "height",
      padX: 3,
      padY: 3,
    },
  },
  {
    key: "Scale",
    label: "Scale",
    icon: SlidersHorizontal,
    category: "Input",
    ctor: "tk.Scale",
    varPrefix: "scale",
    font: FONT,
    props: [
      pText("label", "label", "Label"),
      pNumber("from_", "from_", "From", { group: "Behavior", max: 100000 }),
      pNumber("to", "to", "To", {
        group: "Behavior",
        default: 100,
        max: 100000,
      }),
      pNumber("resolution", "resolution", "Step", {
        group: "Behavior",
        default: 1,
        min: 1,
        max: 1000,
      }),
      ...fontProps(10),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background"),
      pColor("troughcolor", "troughcolor", "Trough", { default: "#d1d5db" }),
      ...border(1),
      pSelect("orient", "orient", "Orientation", ORIENT, {
        default: "horizontal",
      }),
      pNumber("length", "length", "Length", { default: 200, max: 4096 }),
      pNumber("width", "width", "Thickness", { default: 15, max: 200 }),
      pBool("showvalue", "showvalue", "Show value", { default: true }),
    ],
    visual: {
      shape: "slider",
      text: "label",
      fg: "fg",
      bg: "bg",
      track: "troughcolor",
      accent: "fg",
      fontSize: "font_size",
      width: "length",
      boxWidth: 200,
    },
  },
  {
    key: "Spinbox",
    label: "Spinbox",
    icon: Hash,
    category: "Input",
    ctor: "tk.Spinbox",
    varPrefix: "spinbox",
    sizing: "chars",
    font: FONT,
    props: [
      pNumber("from_", "from_", "From", { group: "Behavior", max: 100000 }),
      pNumber("to", "to", "To", {
        group: "Behavior",
        default: 100,
        max: 100000,
      }),
      pNumber("increment", "increment", "Step", {
        group: "Behavior",
        default: 1,
        min: 1,
        max: 1000,
      }),
      ...fontProps(12),
      pColor("fg", "fg", "Text color", { default: "#000000" }),
      pColor("bg", "bg", "Background", { default: "#ffffff" }),
      pColor("buttonbackground", "buttonbackground", "Buttons"),
      ...border(2),
      pSelect("justify", "justify", "Justify", JUSTIFY, { default: "left" }),
      pNumber("width", "width", "Width", {
        unit: "chars",
        default: 10,
        max: 400,
      }),
    ],
    visual: {
      shape: "field",
      fallbackText: "0",
      fg: "fg",
      bg: "bg",
      fontSize: "font_size",
      fontFamily: "font_family",
      borderWidth: "borderwidth",
      width: "width",
      padX: 4,
      padY: 3,
    },
  },
  {
    key: "Frame",
    label: "Frame",
    icon: FrameIcon,
    category: "Layout",
    ctor: "tk.Frame",
    varPrefix: "frame",
    sizing: "px",
    props: [
      pColor("bg", "bg", "Background", { default: "#e5e7eb" }),
      ...border(1),
      pColor("highlightbackground", "highlightbackground", "Outline"),
      pNumber("highlightthickness", "highlightthickness", "Outline width", {
        group: "Appearance",
        max: 40,
      }),
      pNumber("width", "width", "Width", { default: 200, min: 10 }),
      pNumber("height", "height", "Height", { default: 120, min: 10 }),
      pNumber("padx", "padx", "Pad X", { group: "Layout", max: 200 }),
      pNumber("pady", "pady", "Pad Y", { group: "Layout", max: 200 }),
    ],
    visual: {
      shape: "box",
      bg: "bg",
      borderWidth: "borderwidth",
      borderColor: "highlightbackground",
      width: "width",
      height: "height",
      boxWidth: 200,
      boxHeight: 120,
    },
  },
  {
    key: "Canvas",
    label: "Canvas",
    icon: PenTool,
    category: "Layout",
    ctor: "tk.Canvas",
    varPrefix: "canvas",
    sizing: "px",
    props: [
      pColor("bg", "bg", "Background", { default: "#ffffff" }),
      ...border(1),
      pColor("highlightbackground", "highlightbackground", "Outline", {
        default: "#d1d5db",
      }),
      pNumber("highlightthickness", "highlightthickness", "Outline width", {
        group: "Appearance",
        default: 1,
        max: 40,
      }),
      pNumber("width", "width", "Width", { default: 240, min: 10 }),
      pNumber("height", "height", "Height", { default: 160, min: 10 }),
    ],
    visual: {
      shape: "box",
      fallbackText: "Canvas",
      bg: "bg",
      borderWidth: "borderwidth",
      borderColor: "highlightbackground",
      width: "width",
      height: "height",
      boxWidth: 240,
      boxHeight: 160,
    },
  },
  {
    key: "LabelFrame",
    label: "LabelFrame",
    icon: AlignLeft,
    category: "Layout",
    ctor: "tk.LabelFrame",
    varPrefix: "labelframe",
    sizing: "px",
    font: FONT,
    props: [
      pText("text", "text", "Title", { default: "Group" }),
      ...fontProps(12),
      pColor("fg", "fg", "Title color", { default: "#000000" }),
      pColor("bg", "bg", "Background"),
      ...border(2),
      pSelect("labelanchor", "labelanchor", "Title anchor", ANCHOR, {
        default: "nw",
      }),
      pNumber("width", "width", "Width", { default: 220, min: 10 }),
      pNumber("height", "height", "Height", { default: 140, min: 10 }),
    ],
    visual: {
      shape: "box",
      text: "text",
      fg: "fg",
      bg: "bg",
      borderWidth: "borderwidth",
      fontSize: "font_size",
      fontFamily: "font_family",
      width: "width",
      height: "height",
      boxWidth: 220,
      boxHeight: 140,
    },
  },
];

export const TKINTER: FrameworkDef = {
  id: "tkinter",
  label: "Tkinter",
  shortLabel: "Tk",
  tagline: "Python standard library toolkit",
  module: "tkinter",
  alias: "tk",
  docsUrl: "https://docs.python.org/3/library/tkinter.html",
  accent: "#8b9dc3",
  widgets,
  categories: ["Display", "Input", "Layout"],
  defaultWindow: { width: 900, height: 600, background: "#f0f0f0" },
};
